version: 1.0.{build}-{branch}

branches:
  except:
    - gh-pages
    - master

skip_tags: true

skip_commits:
  files:
    - docs/*
    - docs/*/*
    - .github/*
    - .github/*/*
    - LICENSE
    - README.md
    - .azure-pipelines.yml
    - .travis.yml

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019

build_script:
  - |-
      echo This link is outdated. Use this one instead: https://github.com/xenia-canary/xenia-canary/releases/latest/download/xenia-canary.zip > README.txt
      7z a xenia-%appveyor_repo_branch%.zip README.txt
      7z a xenia-vfs-dump-%appveyor_repo_branch%.zip README.txt

test: off

artifacts:
  - path: xenia-$(appveyor_repo_branch).zip
  - path: xenia-vfs-dump-$(appveyor_repo_branch).zip

deploy: off
