version: 1.0.{build}-{branch}

branches:
  except:
    - gh-pages
    - master

skip_tags: true

skip_commits:
  files:
    - docs/*
    - docs/*/*
    - .github/*
    - .github/*/*
    - src/**/*_posix.*
    - src/**/*_linux.*
    - src/**/*_x11.*
    - src/**/*_gtk.*    
    - LICENSE
    - README.md
    - .azure-pipelines.yml
    - .travis.yml

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019

init:
  - wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status

install:
  - xb setup

build_script:
  - xb build --target=src\xenia-app --target=src\xenia-vfs-dump

after_build:
  - |-
      7z a xenia-%appveyor_repo_branch%.zip LICENSE .\build\bin\Windows\Release\xenia-canary.exe
      7z a xenia-vfs-dump-%appveyor_repo_branch%.zip LICENSE .\build\bin\Windows\Release\xenia-vfs-dump.exe
      7z a SDL2.zip .\build\bin\Windows\Release\SDL2.dll

test: off

artifacts:
  - path: xenia-$(appveyor_repo_branch).zip
  - path: xenia-vfs-dump-$(appveyor_repo_branch).zip
  - path: SDL2.zip

deploy: off
