name: CI

on:
  push:
    branches-ignore: [gh-pages, master]
    paths-ignore:
      - '.clang-format'
      - '.drone.star'
      - '.gitattributes'
      - '.gitignore'
      - '.gdbinit'
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
      - '*.yml'
      - 'docs/**'
      - 'src/**/*_posix.*'
      - 'src/**/*_linux.*'
      - 'src/**/*_gnulinux.*'
      - 'src/**/*_x11.*'
      - 'src/**/*_gtk.*'
      - 'src/**/*_android.*'
      - 'src/**/*_mac.*'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches-ignore: [gh-pages, master]
    paths-ignore:
      - '.clang-format'
      - '.drone.star'
      - '.gitattributes'
      - '.gitignore'
      - '.gdbinit'
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
      - '*.yml'
      - 'docs/**'
      - 'src/**/*_posix.*'
      - 'src/**/*_linux.*'
      - 'src/**/*_gnulinux.*'
      - 'src/**/*_x11.*'
      - 'src/**/*_gtk.*'
      - 'src/**/*_android.*'
      - 'src/**/*_mac.*'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ${{ matrix.runs-on }}
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2019, windows-latest]
        include:
          - runs-on: windows-2019
            vsver: VS2019
          - runs-on: windows-latest
            vsver: VS2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        run: .\xb setup
      - name: Build
        run: .\xb build --config=Release --target=src\xenia-app --target=src\xenia-vfs-dump
      - name: Prepare artifacts
        run: |
          robocopy . build\bin\${{ runner.os }}\Release                                                                LICENSE /r:0 /w:0
          robocopy   build\bin\${{ runner.os }}\Release artifacts\xenia_canary   xenia_canary.exe   xenia_canary.pdb   LICENSE /r:0 /w:0
          robocopy   build\bin\${{ runner.os }}\Release artifacts\xenia-vfs-dump xenia-vfs-dump.exe xenia-vfs-dump.pdb LICENSE /r:0 /w:0
          curl -fLJO https://github.com/xenia-canary/game-patches/archive/refs/heads/main.zip
          7z e game-patches-main.zip game-patches-main\patches -oartifacts\xenia_canary\patches
      - name: Upload xenia-vfs-dump artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xenia-vfs-dump_canary_${{ matrix.vsver }}
          path: artifacts\xenia-vfs-dump
          if-no-files-found: error
      - name: Upload xenia artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xenia_canary_${{ matrix.vsver }}
          path: artifacts\xenia_canary
          if-no-files-found: error
      - name: Create release
        if: |
          matrix.runs-on == 'windows-2019' &&
          github.repository == 'xenia-canary/xenia-canary' &&
          github.event.action != 'pull_request' &&
          contains(github.ref, 'refs/heads/canary') &&
          github.ref != 'refs/heads/canary_base'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $asset="xenia_canary.zip"
          7z a $asset .\artifacts\xenia_canary\*.exe LICENSE
          If ($(Get-Item $asset).length -le 100000) {
            Throw "Error: Archive $asset too small!"
          }
          $tag=$env:GITHUB_SHA.SubString(0,7)
          $branch=$($env:GITHUB_REF -replace 'refs/heads/', '')
          $title="${tag}_$branch"
          gh release create $tag $asset --target $env:GITHUB_SHA -t $title
          # Remove canary_ to prevent conflicts from tag
          $tag=$($branch -replace 'canary_', '')
          gh release delete $tag -y
          git push --delete origin $tag
          git tag -d $tag
          gh release create $tag $asset --target $env:GITHUB_SHA -t $branch
